// Package files holds the workflow file store: where a step's bytes live
// between steps, and between the runner that writes them and the API that
// serves them.
//
// Two services need the same bytes and never share a process — the runner
// writes a file, enact-main streams it to a browser — so "the file" cannot be
// a buffer passed along in memory, and cannot be a path only one of them can
// resolve. What travels between steps is a File descriptor: a reference plus
// enough metadata to decide what to do with it, small enough to sit inside a
// step's ordinary JSON output.
//
// Bytes are addressed by a reference of the form "<scheme>:<key>". The scheme
// selects the store, which is what lets a deployment gain object storage later
// without rewriting the executions it has already recorded: an old "fs:"
// reference stays readable beside a new one.
package files

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strings"
)

// MaxFileSize caps one stored file. It is enforced while writing, which is
// the only place the whole stream is seen, so an oversized upload fails
// against a limit rather than against the disk.
const MaxFileSize = 100 << 20 // 100 MiB

// DefaultMimeType is what an unlabelled file is stored as. Browsers download
// it rather than guessing, which is the right default for content the
// platform did not produce.
const DefaultMimeType = "application/octet-stream"

// Errors callers are expected to distinguish. Anything else is wrapped with
// the package name and treated as a failure of the store itself.
var (
	// ErrNotFound is returned for a reference with nothing behind it.
	ErrNotFound = errors.New("files: not found")
	// ErrTooLarge is returned when a write exceeds MaxFileSize. The partial
	// file is removed before it is returned.
	ErrTooLarge = errors.New("files: file exceeds the size limit")
	// ErrBadReference is returned for a reference that is malformed, or whose
	// key is not a location this package would ever have written.
	ErrBadReference = errors.New("files: malformed reference")
)

// Location says where a file belongs, which is what decides when it dies.
//
// Files are keyed to a location rather than to the step that made them:
// nothing refcounts them, so cleanup is deleting a prefix rather than working
// out which of several steps still refers to a given file.
type Location struct {
	WorkflowID string
	// ExecutionID scopes a file to one run, which is the common case: it is
	// deleted with that execution. Empty means the file is RETAINED — it
	// outlives every run and is deleted only when the workflow itself is.
	ExecutionID string
}

// InExecution returns the location of a file belonging to one run.
func InExecution(workflowID, executionID string) Location {
	return Location{WorkflowID: workflowID, ExecutionID: executionID}
}

// InWorkflow returns the location of a retained file: one a run produced but
// which is meant to outlast it.
func InWorkflow(workflowID string) Location {
	return Location{WorkflowID: workflowID}
}

// IsRetained reports whether this location outlives a single execution.
func (l Location) IsRetained() bool { return l.ExecutionID == "" }

// Valid reports whether the location's ids are usable as path segments. Ids
// are generated by the platform, so this is a guard against a caller passing
// something empty or hand-made rather than a check on untrusted input.
func (l Location) Valid() bool {
	if !validSegment(l.WorkflowID) {
		return false
	}
	return l.ExecutionID == "" || validSegment(l.ExecutionID)
}

// prefix is the key prefix every file at this location shares. It is also
// what DeleteAt removes, so the layout and the cleanup cannot disagree.
func (l Location) prefix() string {
	if l.IsRetained() {
		return workflowPrefix(l.WorkflowID) + "/files"
	}
	return workflowPrefix(l.WorkflowID) + "/executions/" + l.ExecutionID + "/files"
}

// workflowPrefix is what every one of a workflow's files sits under, whichever
// kind it is. Removing it removes them all, which is what makes deleting a
// workflow a single operation.
func workflowPrefix(workflowID string) string {
	return "workflows/" + workflowID
}

// Metadata is what is known about a file without reading it.
type Metadata struct {
	// Name is the file's display name — shown to a person, offered when
	// downloading. It never appears in the key: the key is a UUID, so a
	// hostile name cannot reach the filesystem.
	Name     string `json:"name,omitempty"`
	MimeType string `json:"mime_type"`
	Size     int64  `json:"size"`
}

// File is a reference to stored bytes, carried inside a step's ordinary JSON
// output.
//
// It is a value, not a side channel: a code step receives it as a plain
// object and can pass it along, put it in an array or drop it, without the
// runner treating files as a separate kind of thing. It cannot read the bytes
// — goja has no I/O — which is the point. Only a step that declares it works
// with files ever touches content.
//
// The "$file" key is the marker. A dollar-prefixed name is not something an
// author would write for a field of their own, so finding every file in an
// arbitrary output is a walk looking for one key rather than a guess at a
// shape.
type File struct {
	Ref      string `json:"$file"`
	Name     string `json:"name,omitempty"`
	MimeType string `json:"mime_type"`
	Size     int64  `json:"size"`
}

// FileSchema is the JSON Schema of a File, for a step that declares one in
// its output_schema.
//
// Exported so the shape an editor completes against and the shape the runner
// writes come from one definition. Two descriptions of the same thing are two
// descriptions that eventually disagree.
func FileSchema() json.RawMessage {
	return json.RawMessage(`{
	"type": "object",
	"description": "A file produced by a step, stored by reference.",
	"properties": {
		"$file": {"type": "string", "description": "Storage reference for the file's bytes"},
		"name": {"type": "string", "description": "Display name, shown when downloading"},
		"mime_type": {"type": "string"},
		"size": {"type": "integer", "description": "Size in bytes"}
	},
	"required": ["$file", "mime_type"]
}`)
}

// Store holds file bytes for workflow executions.
//
// Streams rather than byte slices throughout: an exported document is
// arbitrarily large and nothing here has a reason to hold a whole one in
// memory. The one operation that must see every byte — enforcing the size
// limit — does it while copying.
type Store interface {
	// Scheme prefixes every reference this store creates, and is how a
	// reference is later routed back to it.
	Scheme() string

	// Put stores r at loc and returns the descriptor for it. The store
	// assigns the key; callers never construct one. Size on the returned
	// File is what was actually written, not what the caller claimed.
	Put(ctx context.Context, loc Location, r io.Reader, meta Metadata) (File, error)

	// Open streams a stored file. The caller closes it.
	Open(ctx context.Context, ref string) (io.ReadCloser, error)

	// Stat reports what is known about a file without opening it.
	Stat(ctx context.Context, ref string) (Metadata, error)

	// Copy duplicates a file into another location and returns the new
	// reference. This is how a file outlives the run that made it: the run's
	// own files go when the execution does, so anything meant to be kept is
	// copied to a retained location first.
	Copy(ctx context.Context, dst Location, ref string) (File, error)

	// DeleteAt removes every file at a location. Cleanup is by location
	// rather than by reference, so an execution that failed halfway through
	// still leaves nothing behind. Deleting a location with nothing in it is
	// not an error.
	DeleteAt(ctx context.Context, loc Location) error

	// DeleteWorkflow removes every file a workflow ever produced: its
	// retained files AND those of all its executions.
	//
	// One call rather than a walk over executions, because both kinds nest
	// under the workflow in the key layout — and because execution records
	// are deleted by query, leaving no list of ids to iterate afterwards. A
	// workflow with no files is not an error.
	DeleteWorkflow(ctx context.Context, workflowID string) error
}

// ParseRef splits a reference into its scheme and the location the file
// belongs to.
//
// This is the authorization hook as much as a parser. A reference names bytes
// but says nothing about who may read them, so the API resolves the location
// here and checks THAT against the caller's permissions — never the reference
// itself. A reference from another organization's run parses perfectly well;
// what stops it is that its workflow is not one the caller may view.
func ParseRef(ref string) (scheme string, loc Location, err error) {
	scheme, key, found := strings.Cut(ref, ":")
	if !found || scheme == "" {
		return "", Location{}, fmt.Errorf("%w: %q", ErrBadReference, ref)
	}
	loc, err = parseKey(key)
	if err != nil {
		return "", Location{}, err
	}
	return scheme, loc, nil
}

// parseKey validates a key against the two layouts this package writes and
// returns the location it encodes.
//
// Strict by construction: a key is accepted only if it matches one of the
// layouts exactly, segment for segment. That leaves no room for traversal, an
// absolute path or a stray separator, because such a key is not a shape this
// function admits at all — rather than one it tries to sanitise.
func parseKey(key string) (Location, error) {
	bad := func() (Location, error) {
		return Location{}, fmt.Errorf("%w: key %q", ErrBadReference, key)
	}

	segments := strings.Split(key, "/")
	for _, segment := range segments {
		if !validSegment(segment) {
			return bad()
		}
	}

	switch {
	// workflows/{id}/executions/{id}/files/{uuid}
	case len(segments) == 6 &&
		segments[0] == "workflows" && segments[2] == "executions" && segments[4] == "files":
		return InExecution(segments[1], segments[3]), nil

	// workflows/{id}/files/{uuid}
	case len(segments) == 4 && segments[0] == "workflows" && segments[2] == "files":
		return InWorkflow(segments[1]), nil
	}
	return bad()
}

// validSegment reports whether s is usable as one path segment.
//
// The allowed set is deliberately narrower than what a filesystem accepts:
// platform ids are UUIDs and keys are UUIDs, so anything outside this set is
// not a value this package produced.
func validSegment(s string) bool {
	if s == "" || s == "." || s == ".." {
		return false
	}
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case r == '-', r == '_', r == '.':
		default:
			return false
		}
	}
	return true
}

// normalize fills in the defaults a caller may leave out, so what is stored
// is always answerable.
func (m Metadata) normalize() Metadata {
	if m.MimeType == "" {
		m.MimeType = DefaultMimeType
	}
	return m
}
