// s2s-keygen generates the local S2S key material: one Ed25519 keypair per
// service under s2s/keys/<service>.key (PEM PKCS#8, never committed), the
// combined public JWKS at s2s/jwks.yaml, and the combined private-key
// bundle at s2s/private-keys.yaml (gitignored) that enact-tests loads via
// S2S_PRIVATE_KEYS_FILE to impersonate the fleet.
//
// It is idempotent: existing private keys are kept (so already-distributed
// tokens keep verifying) and the JWKS is rebuilt from whatever keys exist.
// Delete a key file and re-run to rotate one service.
//
//	go run ./scripts/s2s-keygen        (or: make s2s-keygen)
package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

var services = []string{
	"enact-agent-management-api",
	"enact-kb-api",
	"enact-kb-document-indexer",
	"enact-main",
	"enact-model-inference",
	"enact-model-management",
	"enact-tests",
}

func main() {
	keyDir := filepath.Join("s2s", "keys")
	if err := os.MkdirAll(keyDir, 0o700); err != nil {
		log.Fatalf("create %s: %v", keyDir, err)
	}

	jwks := "# Public keys of every enact service, one entry per service.\n" +
		"# Generated by scripts/s2s-keygen — do not edit by hand; private\n" +
		"# keys live in s2s/keys/ (gitignored).\n" +
		"keys:\n"
	privateKeys := "# Private keys of EVERY enact service — the impersonation bundle\n" +
		"# for enact-tests (S2S_PRIVATE_KEYS_FILE). Generated by\n" +
		"# scripts/s2s-keygen; gitignored, never distribute beyond the\n" +
		"# tests service.\n" +
		"keys:\n"

	for _, svc := range services {
		keyPath := filepath.Join(keyDir, svc+".key")
		priv, created, err := loadOrCreateKey(keyPath)
		if err != nil {
			log.Fatalf("%s: %v", svc, err)
		}
		pubDER, err := x509.MarshalPKIXPublicKey(priv.Public().(ed25519.PublicKey))
		if err != nil {
			log.Fatalf("%s: marshal public key: %v", svc, err)
		}
		pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER})

		jwks += fmt.Sprintf("  - kid: %s\n    algorithm: EdDSA\n    public_key: |\n", svc)
		for _, line := range splitLines(string(pubPEM)) {
			jwks += "      " + line + "\n"
		}

		privDER, err := x509.MarshalPKCS8PrivateKey(priv)
		if err != nil {
			log.Fatalf("%s: marshal private key: %v", svc, err)
		}
		privPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: privDER})
		privateKeys += fmt.Sprintf("  - kid: %s\n    private_key: |\n", svc)
		for _, line := range splitLines(string(privPEM)) {
			privateKeys += "      " + line + "\n"
		}

		state := "kept"
		if created {
			state = "generated"
		}
		fmt.Printf("%-30s %s (%s)\n", svc, keyPath, state)
	}

	jwksPath := filepath.Join("s2s", "jwks.yaml")
	if err := os.WriteFile(jwksPath, []byte(jwks), 0o644); err != nil {
		log.Fatalf("write %s: %v", jwksPath, err)
	}
	fmt.Printf("wrote %s\n", jwksPath)

	privateKeysPath := filepath.Join("s2s", "private-keys.yaml")
	if err := os.WriteFile(privateKeysPath, []byte(privateKeys), 0o600); err != nil {
		log.Fatalf("write %s: %v", privateKeysPath, err)
	}
	fmt.Printf("wrote %s\n", privateKeysPath)
}

func loadOrCreateKey(path string) (ed25519.PrivateKey, bool, error) {
	if data, err := os.ReadFile(path); err == nil {
		block, _ := pem.Decode(data)
		if block == nil {
			return nil, false, fmt.Errorf("existing key is not valid PEM")
		}
		parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err != nil {
			return nil, false, fmt.Errorf("parse existing key: %w", err)
		}
		key, ok := parsed.(ed25519.PrivateKey)
		if !ok {
			return nil, false, fmt.Errorf("existing key is %T, want Ed25519", parsed)
		}
		return key, false, nil
	}

	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, false, err
	}
	der, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return nil, false, err
	}
	pemBytes := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der})
	if err := os.WriteFile(path, pemBytes, 0o600); err != nil {
		return nil, false, err
	}
	return priv, true, nil
}

func splitLines(s string) []string {
	var out []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			if i > start {
				out = append(out, s[start:i])
			}
			start = i + 1
		}
	}
	if start < len(s) {
		out = append(out, s[start:])
	}
	return out
}